services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:80"
    volumes:
      - ./backend:/code
