services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.prod
    ports:
      - "80:3000"
  
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.prod
