
name: English to German translator CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: make .env file available
      run:  |
          cp /home/ubuntu/my-backend.env backend/.env
    - name: Copy model file
      run: cp /home/ubuntu/model_english_to_german.pt backend/translation_model_inference
    - name: build the docker compose image
      run: sudo docker compose -f docker-compose-prod.yaml build --no-cache
    - name: Stop existing docker compose container and delete images
      run: sudo docker compose -f docker-compose-prod.yaml down # --rmi local
    - name: run the docker compose container on port 80 and bye bye
      run: sudo docker compose -f docker-compose-prod.yaml up
